logging.level:
  it.mltk.poc.axonpms: DEBUG
  it.mltk.poc.axonpms.delivery: TRACE
#  org.hibernate.SQL: DEBUG
#  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server.port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver